analysis:
  backaction_map:
    arrow_length_multiplier: 1.5
    color_max: 0.06
    color_min: 0.0
  bin_size: 0.1
  derivative_order: 1
  hamiltonian_map:
    arrow_length_multiplier: 1.25
    fit_guess:
    - 100000.0
    - 0.0
    omega_fixed: true
  subdir: /media/qnl/Extreme SSD/Gate diagnosis/2020_11_19/SQG_RNN_1000_ns_err_amp_0.0000_leakage_ratio_0.00/analysis/210212_132157_all_prep_states_dt_2ns
  sweep_time: false
  t_max: null
  t_min: null
  trajectory_dt: 2.0e-09
  x_for_yz_fit: null
  y_for_xz_fit: null
  z_for_xy_fit: null
figure_options:
  bbox_inches: tight
  dpi: 200
  pad_inches: 0.05
  transparent: true
prep:
  compress_output_file: true
  iq_scaling: 0.005
  output_filename: training_validation_split.h5
  training_validation_ratio: 0.9
training:
  annealing_steps: 2
  bidirectional: false
  epochs_per_anneal: 8
  experiment_id: all_prep_states_dt_2ns
  learning_rate_epoch_constant: 3
  learning_rate_init: 0.001
  learning_rate_reduce_after: 0
  lstm_neurons: 32
  mask_value: -1.0
  mini_batch_size: 512
  prep_state_from_ro: true
voltage_records:
  data_points_for_prep_state: 20
  filename: all_prep_states_dt_2ns_meas_XYZ.h5
  filepath: /media/qnl/Extreme SSD/Gate diagnosis/2020_11_19/SQG_RNN_1000_ns_err_amp_0.0000_leakage_ratio_0.00
  multiple_prep_states: true
  n_levels: 2
  num_features: 2
  prep_states:
  - g
  - e
  - +Y
  - -Y
