analysis:
  backaction_map:
    arrow_length_multiplier: 1.5
    color_max: 0.06
    color_min: 0.0
  bin_size: 0.1
  derivative_order: 1
  hamiltonian_map:
    arrow_length_multiplier: 1.25
    fit_guess:
    - 100000.0
    - 0.0
    omega_fixed: false
  subdir: /run/media/qnl/Seagate Expansion Drive/non_markovian/local_data/2021_02_27/cr_trajectories_test_029/data_transfer/2021_02_27/cr_trajectories_test_029/analysis/210301_231333_prep_C+X_T+Y
  sweep_time: false
  t_max: null
  t_min: null
  trajectory_dt: 5.0e-09
  x_for_yz_fit: 0.0
  y_for_xz_fit: null
  z_for_xy_fit: null
figure_options:
  bbox_inches: tight
  dpi: 200
  pad_inches: 0.05
  transparent: true
prep:
  iq_scaling: 0.005
  output_filename: training_validation_split.h5
  training_validation_ratio: 0.9
training:
  epochs: 30
  experiment_id: prep_C+X_T+Y
  lstm_neurons: 32
  mask_value: -1.0
  mini_batch_size: 1024
voltage_records:
  data_points_for_prep_state: 1
  filename: 18-25-21-2813_cr_trajectories_test_029
  filepath: /run/media/qnl/Seagate Expansion Drive/non_markovian/local_data/2021_02_27/cr_trajectories_test_029/data_transfer/2021_02_27/cr_trajectories_test_029
  num_features: 2
  prep_state: +X
  strong_ro_dt: 3.0e-08
loading:
  target_prep_state: +Y
  control_prep_state: +X

